/**
 * Verbatim excerpts from Path of Building's Data/ModExplicit.lua and Data/ModMaster.lua.
 *
 * Copied unedited so the parser is exercised against the real file format on machines with
 * no Path of Building installed. Regenerate by copying the matching lines across again.
 */

export const MOD_EXPLICIT_EXCERPT = `-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	["LocalIncreasedEnergyShieldPercentAndStunRecovery1"] = { type = "Prefix", affix = "Pixie's", "(6-13)% increased Energy Shield", "(6-7)% increased Stun and Block Recovery", statOrder = { 1585, 1928 }, level = 3, group = "LocalEnergyShieldAndStunRecoveryPercent", weightKey = { "int_armour", "default", }, weightVal = { 1000, 0 }, modTags = { "defences", "energy_shield" }, tradeHashes = { [4015621042] = { "(6-13)% increased Energy Shield" }, [2511217560] = { "(6-7)% increased Stun and Block Recovery" }, } },
	["LocalIncreasedEnergyShieldPercent1"] = { type = "Prefix", affix = "Protective", "(11-28)% increased Energy Shield", statOrder = { 1585 }, level = 3, group = "LocalEnergyShieldPercent", weightKey = { "int_armour", "default", }, weightVal = { 1000, 0 }, modTags = { "defences", "energy_shield" }, tradeHashes = { [4015621042] = { "(11-28)% increased Energy Shield" }, } },
	["ChaosResist5"] = { type = "Suffix", affix = "of Exile", "+(26-30)% to Chaos Resistance", statOrder = { 1667 }, level = 65, group = "ChaosResistance", weightKey = { "armour", "ring", "amulet", "belt", "quiver", "default", }, weightVal = { 250, 250, 250, 250, 250, 0 }, modTags = { "chaos", "resistance" }, tradeHashes = { [2923486259] = { "+(26-30)% to Chaos Resistance" }, } },
	["ChaosResist6"] = { type = "Suffix", affix = "of Bameth", "+(31-35)% to Chaos Resistance", statOrder = { 1667 }, level = 81, group = "ChaosResistance", weightKey = { "armour", "ring", "amulet", "belt", "quiver", "default", }, weightVal = { 250, 250, 250, 250, 250, 0 }, modTags = { "chaos", "resistance" }, tradeHashes = { [2923486259] = { "+(31-35)% to Chaos Resistance" }, } },
	["Strength1"] = { type = "Suffix", affix = "of the Brute", "+(8-12) to Strength", statOrder = { 1203 }, level = 1, group = "Strength", weightKey = { "ring", "amulet", "belt", "str_armour", "str_dex_armour", "str_int_armour", "str_dex_int_armour", "sword", "mace", "sceptre", "staff", "axe", "default", }, weightVal = { 1000, 1000, 1000, 1000, 500, 500, 333, 500, 1000, 500, 500, 500, 0 }, modTags = { "attribute" }, tradeHashes = { [4080418644] = { "+(8-12) to Strength" }, } },
	["LocalBaseArmourAndEvasionRatingAndLife1"] = { type = "Prefix", affix = "Rhoa's", "+(8-10) to Armour", "+(8-10) to Evasion Rating", "+(18-23) to maximum Life", statOrder = { 1565, 1573, 1594 }, level = 30, group = "LocalBaseArmourEvasionRatingAndLife", weightKey = { "default", }, weightVal = { 0 }, modTags = { "resource", "life", "defences", "armour", "evasion" }, tradeHashes = { [3484657501] = { "+(8-10) to Armour" }, [3299347043] = { "+(18-23) to maximum Life" }, [53045048] = { "+(8-10) to Evasion Rating" }, } },
	["PhysicalAttackDamageTakenUber1_"] = { type = "Suffix", affix = "of Shaping", "-(35-25) Physical Damage taken from Attack Hits", statOrder = { 2260 }, level = 68, group = "PhysicalAttackDamageTaken", weightKey = { "belt_shaper", "default", }, weightVal = { 800, 0 }, modTags = { "influence_mod", "physical", "attack" }, tradeHashes = { [3441651621] = { "-(35-25) Physical Damage taken from Attack Hits" }, } },
}
`;

export const MOD_MASTER_EXCERPT = `-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	{ type = "Prefix", affix = "Upgraded", modTags = { "resource", "life" }, "+(15-25) to maximum Life", statOrder = { 1594 }, level = 15, group = "IncreasedLife", types = { ["Body Armour"] = true, ["Gloves"] = true, ["Boots"] = true, ["Helmet"] = true, ["Shield"] = true, ["Ring"] = true, ["Amulet"] = true, ["Belt"] = true, ["Quiver"] = true, }, },
	{ type = "Suffix", affix = "of Craft", modTags = { "elemental", "fire", "resistance" }, "+(16-20)% to Fire Resistance", statOrder = { 1651 }, level = 15, group = "FireResistance", types = { ["Body Armour"] = true, ["Gloves"] = true, ["Boots"] = true, ["Helmet"] = true, ["Shield"] = true, ["Ring"] = true, ["Amulet"] = true, ["Belt"] = true, ["Quiver"] = true, }, },
	{ type = "Suffix", affix = "of Craft", modTags = { "elemental", "fire", "resistance" }, "+(29-35)% to Fire Resistance", statOrder = { 1651 }, level = 50, group = "FireResistance", types = { ["Body Armour"] = true, ["Gloves"] = true, ["Boots"] = true, ["Helmet"] = true, ["Shield"] = true, ["Belt"] = true, ["Quiver"] = true, }, },
	{ type = "Prefix", affix = "Upgraded", modTags = { "physical_damage", "chaos_damage", "bleed", "poison", "unveiled_mod", "damage", "physical", "chaos", "attack", "ailment" }, "(81-85)% increased Physical Damage", "(13-15)% chance to Poison on Hit", statOrder = { 1258, 8127 }, level = 60, group = "LocalIncreasedPhysicalDamageAndPoisonChance", types = { ["Dagger"] = true, ["One Handed Axe"] = true, ["One Handed Mace"] = true, ["One Handed Sword"] = true, ["Claw"] = true, ["Sceptre"] = true, ["Thrusting One Handed Sword"] = true, ["Two Handed Axe"] = true, ["Two Handed Mace"] = true, ["Two Handed Sword"] = true, ["Staff"] = true, ["Wand"] = true, ["Bow"] = true, }, },
}
`;
